include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false,
    sort_pub_dependencies: false,
    prefer_const_constructors: True,
    prefer_const_constructors_in_immutables: True,
    prefer_const_literals_to_create_immutables: True,
    prefer_const_constructors_in_literals: True,
    prefer_typing_uninitialized_variables: True,
    prefer_final_fields: True,
    prefer_final_locals: True,
    prefer_is_empty: True,
    prefer_is_not_empty: True,
    prefer_single_quotes: True,
